### ISSUE TITLE
Changes for ASP.NET Core 2.0

### ISSUE THREAD

**Issue by MV10** [tillig/DataProtection#1]
Travis, I wanted to thank you for posting this almost two years ago. I can't believe MS is ok with the problem this addresses -- or that the docs don't at least explain that the cert-object and PFX overrides for `ProtectKeysWithCertificate` are effectively useless. Only about a month ago they blew off somebody's request for help with vague handwaving about "framework limitations" -- and yet here we are with a simple, working example... from two years ago.  Anyway, enough ranting.

I don't have time to convert to VS2017 and do a PR, but I thought I'd post the changes needed to integrate with ASP.NET Core 2.0. They changed how the encryptor is registered, apparently. (Also, for anyone wanting to target netcore instead of netframework, change the four references to `RSACryptoServiceProvider` in the encryptor and decryptor classes to just `RSA` -- everything else works after that.)

```
public static IDataProtectionBuilder ProtectKeysWithProvidedCertificate(this IDataProtectionBuilder builder, X509Certificate2 certificate)
{
    if(certificate == null)
    {
        throw new ArgumentNullException(nameof(certificate));
    }

    // save the certificate to DI
    builder.Services.AddSingleton(new CertificateEncryptionOptions(certificate));

    // set up the encryptor (encrypted nodes reference the decryptor by typename)
    builder.Services.AddSingleton<IConfigureOptions<KeyManagementOptions>>(provider =>
    {
        return new ConfigureOptions<KeyManagementOptions>(opts =>
        {
            opts.XmlEncryptor = ActivatorUtilities.CreateInstance<CertificateXmlEncryptor>(provider);
        });
    });

    return builder;
}
```

**Comment by tillig** [comment]
Thanks for this. I should really try to get this solution updated and this will help.

**Comment by MV10** [comment]
No problem. Unfortunately whatever weirdness DPAPI does with DI is still present, I experimentally tried normal DI in the encrypt/decrypt classes but it doesn't work.

**Comment by tillig** [comment]
I just pushed a whole bunch of updates including:
- Update to the latest VS 2017, Roslyn analyzers, project structure.
- Updates for ASP.NET Core 2.0 based on the changes mentioned.
- Targeting netstandard2.0 and using the cross-platform abstractions for certificates and keys.

It unit tests out and seems to round-trip things fine, at least on Windows, but I don't have a test app running for it so YMMV.

Thanks again!
